### ISSUE TITLE
Is there any plan for high-res fix ? 

### ISSUE THREAD

**Issue by Joseph7695** [oneir0mancer/stable-diffusion-diffusers-colab-ui#4]

**Comment by oneir0mancer** [comment]
Maybe at some point, idk. Don't really see a point in hi-res fix beyond convenience, when you can just upscale low-res image and then img2img it.

I mainly work on features that interest me, because I don't have much time to put into this project. But if anyone else wants to contribute, be my guest.

**Comment by oneir0mancer** [comment]
Added img2img pipeline that reuses txt2img components in #8 , basically the same functionality
